name: Update dependencies packages

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Update dependencies
        run: yarn upgrade --latest

      - name: Set git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create pull request
        run: |
          hub add -A
          hub commit -m "chore: Update dependencies packages"
          hub pull-request -b master -m "Update dependencies packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
